# This file is part of Rapid.
# Copyright © 2024-2025 Kaleb A. Ascevich
#
# Rapid is free software: you can redistribute it and/or modify it under the
# terms of the GNU Affero General Public License (GNU AGPL) as published by the
# Free Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# Rapid is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU AGPL for more details.
#
# You should have received a copy of the GNU AGPL along with Rapid. If not, see
# <https://www.gnu.org/licenses/>.

excluded:
  - .build
  - .swiftpm

disabled_rules:
  - comma # more annoying than helpful when aligning code
  - identifier_name # doesn't play well with custom operators
  - line_length
  - todo # annoying
  - vertical_parameter_alignment_on_call # doesn't play well with trailing closures

opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - comma_inheritance
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - direct_return
  - discouraged_assert
  - discouraged_none_name
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fatal_error_message
  - file_header
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - indentation_width
  - inert_defer
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - local_doc_comment
  - lower_acl_than_parent
  - missing_docs
  - modifier_order
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - non_overridable_class_declaration
  - nslocalizedstring_key
  - operator_usage_whitespace
  - optional_enum_case_matching
  - override_in_extension
  - pattern_matching_keywords
  - period_spacing
  - prefer_key_path
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - reduce_into
  - redundant_nil_coalescing
  - redundant_self_in_closure
  - redundant_type_annotation
  - return_value_from_void_function
  - self_binding
  - shorthand_argument
  - shorthand_optional_binding
  - sorted_first_last
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unhandled_throwing_task
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_capture_list
  - unused_parameter
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - weak_delegate
  - yoda_condition

analyzer_rules:
  - capture_variable
  - typesafe_array_init
  - unused_declaration
  - unused_import

trailing_comma:
  mandatory_comma: true

# Trailing whitespace on empty lines lets my tab key live
# just a little bit longer.
trailing_whitespace:
  ignores_empty_lines: true

# There are times when one actually needs to use these for
# their intended purposes.
force_cast: warning
force_try: warning

# Whitespace to the right of colons is used constantly for
# alignment.
colon:
  flexible_right_spacing: true

nesting:
  type_level: 2

indentation_width:
  indentation_width: 2

opening_brace:
  ignore_multiline_statement_conditions: true
  ignore_multiline_function_signatures: true

file_header:
  required_pattern: |
                    \/\/ This file is part of Rapid\.
                    \/\/ Copyright © \d{4}-\d{4} .+
                    \/\/
                    \/\/ Rapid is free software: you can redistribute it and/or modify it under the
                    \/\/ terms of the GNU Affero General Public License \(GNU AGPL\) as published by the
                    \/\/ Free Software Foundation, either version 3 of the License, or \(at your
                    \/\/ option\) any later version\.
                    \/\/
                    \/\/ Rapid is distributed in the hope that it will be useful, but WITHOUT ANY
                    \/\/ WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
                    \/\/ A PARTICULAR PURPOSE\. See the GNU AGPL for more details\.
                    \/\/
                    \/\/ You should have received a copy of the GNU AGPL along with Rapid\. If not, see
                    \/\/ <https:\/\/www\.gnu\.org\/licenses\/>\.
